// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUo1a90mBpe23zKC4h2z1dFpmWAAQD48',
    appId: '1:117198652965:web:2e8a0d1eef9ae207b6a1cc',
    messagingSenderId: '117198652965',
    projectId: 'fir-signin-5b467',
    authDomain: 'fir-signin-5b467.firebaseapp.com',
    storageBucket: 'fir-signin-5b467.appspot.com',
    measurementId: 'G-XCF8WM3NLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB9FEYnLMwAAs1hNiEFscEGL8ZyjYKLlQ',
    appId: '1:117198652965:android:3bc8b5f5dd49f9fdb6a1cc',
    messagingSenderId: '117198652965',
    projectId: 'fir-signin-5b467',
    storageBucket: 'fir-signin-5b467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqS8f0PuWJ5vyNolEby97zCdPoKB7hg8',
    appId: '1:117198652965:ios:317f6bfad4650dd4b6a1cc',
    messagingSenderId: '117198652965',
    projectId: 'fir-signin-5b467',
    storageBucket: 'fir-signin-5b467.appspot.com',
    iosClientId: '117198652965-bpe7hsf9ecq02u4ng175sesm8vmua19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqS8f0PuWJ5vyNolEby97zCdPoKB7hg8',
    appId: '1:117198652965:ios:317f6bfad4650dd4b6a1cc',
    messagingSenderId: '117198652965',
    projectId: 'fir-signin-5b467',
    storageBucket: 'fir-signin-5b467.appspot.com',
    iosClientId: '117198652965-bpe7hsf9ecq02u4ng175sesm8vmua19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorsapp',
  );
}
